### ISSUE TITLE
개발환경 구축

### ISSUE THREAD

**Issue by teang1995** [teang1995/hello-nodejs#1]
nodejs 개발 환경 구축을 하고자 함.
두 가지 방법으로 구축하고 싶은데
1. 서버에서 개발하기
2. 서버의 컨테이너에서 개발하기

두 가지 방법 모두에서 200, ok 를 받는 것까지 다뤄보겠음.

### TODO's
- [ ] 서버에서 nodejs 설치
- [ ] nodejs 공식 홈페이지의 docker image 이용하여 컨테이너 띄우기
- [ ] 두 방법 모두에서 사용할 간단한 REST 서버 만들기
- [ ] 200, ok 받기 - 서버
- [ ] 200, ok 받기 - 컨테이너

**Comment by teang1995** [comment]
[node.js official](https://nodejs.org/ko/download/) 에서 다운로드 파일을 받았음.
source file로 받으면 tar.gz 형식으로 다운 받을 수 있다.

**Comment by teang1995** [comment]
npm 을 설치한다.
`apt install npm` 

설치하려 했는데.. 서버에서는 권한이 막혀 있어서 설치가 안 되니 로컬에서 다운 받아 해보도록 하겠음

**Comment by teang1995** [comment]
![image](https://user-images.githubusercontent.com/23451721/163105154-a29fa2cd-72c7-476c-bba0-857fce34ba2a.png)
우선 윈도우에선 설치 완료

**Comment by teang1995** [comment]
프로젝트 폴더에서 `npm init`
해서 값들을 채워주면 두번째 사진처럼 `package.json` 파일이 생김
![image](https://user-images.githubusercontent.com/23451721/163107063-6c947276-2e89-4fdb-9215-c95664082105.png)
![image](https://user-images.githubusercontent.com/23451721/163107167-448a14ea-e532-43f0-a34d-e9e2e636ec98.png)

**Comment by teang1995** [comment]
`npm install express --save` 로 express 설치해주고나서 
![image](https://user-images.githubusercontent.com/23451721/163107322-5e04be71-7f23-46ae-9509-fa1b87dcf856.png)

`package.json`을 다시 확인해보면 `dependencies` 라는 항목이 아래 사진과 같이 생김.
```json
{
  "name": "hello-nodejs",
  "version": "1.0.0",
  "description": "nodejs test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": ";"
  },
  "keywords": [
    "node.js"
  ],
  "author": "yongtaek.lim",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.3"
  }
}
```
reference
https://waspro.tistory.com/615

**Comment by teang1995** [comment]
express 서버 실행
`express demo`

`cd demo`

`npm install`

`npm start`

**Comment by teang1995** [comment]
두 개의 라우트를 추가함.
```
```

**Comment by teang1995** [comment]
Dockerfile 제작 및 docker image 빌드 완료.
![image](https://user-images.githubusercontent.com/23451721/163116593-3bdc5161-32f3-4eb4-8461-3d9eb766dd1a.png)

**Comment by teang1995** [comment]
docker container를 실행하고, exec을 이용하여 접속하는 것까지 구현 완료.
![image](https://user-images.githubusercontent.com/23451721/163117548-990b04d4-a230-4edb-bb9a-5a728370936c.png)

**Comment by teang1995** [comment]
하지만 LF 때문에 dependencies 빌드에 필요한 파일들이 없다.
`package.json` 에 보니 dependencies가 잘 정리되어 있어 이를 이용해 설치하는 방법을 찾아보던 중 
https://c17an.netlify.app/blog/node.js/npm-install-%EC%A0%95%EB%A6%AC/article/
를 보니 `npm install`을 `package.json`가 있는 폴더에서 실행해주면 dependencies가 알아서 설치된다고 함.

**Comment by teang1995** [comment]
`cd code`

`npm install`

`npm start`

를 이용해 서버를 실행시키고 postman으로 확인.
반응이 잘 오는 것을 볼 수 있음.
![image](https://user-images.githubusercontent.com/23451721/163118436-52f2c6f7-2138-46e1-b57a-ddc596a35a07.png)
이로서 서버에서 컨테이너를 이용해 nodejs 서버를 띄우는 것도 구현하였다.
